spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/alibou_jwt_security_db
    username: developer
    password: developer
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    show-sql: true